# https://stackoverflow.com/a/65236345
name: Merge Bot

on:
  pull_request:
    types: 
      - labeled

env:
  repo: my-wrm/dummy-project
  deploy_label: to deploy
  ready_label: ready to deploy

jobs:
  build:
    if: github.event.label.name == 'to deploy'
    runs-on: ubuntu-latest
    steps:
    - name: merge
      run: |
        echo "label: ${{ env.deploy_label }}"
        echo "Merging... ${{ github.event.pull_request.title }} #${{ github.event.pull_request.number }}"
        gh pr merge ${{ github.event.pull_request.number }} --merge --repo my-wrm/dummy-project
        gh pr edit ${{ github.event.pull_request.number }} --remove-label '${{ env.deploy_label }}' --repo my-wrm/dummy-project
        gh pr edit ${{ github.event.pull_request.number }} --add-label '${{ env.ready_label }}' --repo my-wrm/dummy-project
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

    - name: Send greeting
      run: |
        echo "${{ toJSON(github.event.repository) }}"
        echo ">> ${{ toJSON(github.event.pull_request.full_name) }}"

