name: Auto merge when label to "to deploy" (dev)

on:
  pull_request:
    types: [ labeled ]

env:
  target_branch: preview/dev

jobs:
# github.event.pull_request.head.ref
  build:
    if: github.event.label.name == '[workflow] to deploy' && github.event.pull_request.base.ref == 'preview/dev'
    runs-on: ubuntu-latest

    steps:
    # - uses: actions/checkout@v2
    #   with:
    #     ref: ''
    - name: merge
      run: |
        git config --global user.email "my@wrmsoftware.com"
        git config --global user.name "Merge script"
        git clone https://mywrm:${{ env.access_token }}@github.com/my-wrm/dummy-project.git
        cd dummy-project
        git fetch origin
        git checkout ${{ github.event.pull_request.base.ref }}
        git merge --no-ff origin/${{ github.event.pull_request.head.ref }}
    - name: Send greeting
      run: |
        echo ">> ${{ toJSON(github.event.pull_request) }}"
