name: Auto merge when label to "to deploy" (dev)

on:
  workflow_dispatch:
  pull_request:
    types: [ labeled ]
#     branches: 
#       - preview/dev

jobs:

  build:
#     if: ${{ github.event.label.name == '[workflow] to deploy' }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Send greeting
      run: |
        echo ">> ${{ toJSON(github.event.label.name) }}"
