# https://stackoverflow.com/a/65236345
name: Merge Bot

on:
  pull_request:
    types: 
      - labeled

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: merge
      if: github.event.label.name == 'to deploy'
      run: |
        echo "Merging... ${{ github.event.pull_request.title }} #${{ github.event.pull_request.number }}"
        gh pr merge ${{ github.event.pull_request.number }} --repo my-wrm/dummy-project --merge
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

    - name: Send greeting
      run: |
        echo ">> ${{ toJSON(github.event.pull_request) }}"
