name: Auto merge when label to "to deploy" (dev)

on:
  pull_request:
    types: [ labeled ]

env:
  target_branch: preview/dev

jobs:
# github.event.pull_request.head.ref
  build:
    if: github.event.label.name == '[workflow] to deploy' && github.event.pull_request.base.ref == 'preview/dev'
    runs-on: ubuntu-latest

    steps:
    # - uses: actions/checkout@v2
    #   with:
    #     ref: ''
    # - name: merge
    #   run: |
    #     git config --global user.email "my@wrmsoftware.com"

    - name: Send greeting
      run: |
        echo ">> ${{ toJSON(github.event.pull_request) }}"
