name: Auto merge when label to "to deploy" (dev)

on:
  pull_request:
    types: [ labeled ]
#     branches: 
#       - preview/dev

env:
  target_branch: preview/dev

jobs:
# github.event.pull_request.head.ref
  build:
    if: github.event.label.name == '[workflow] to deploy' && github.event.pull_request.base.ref == 'preview/dev'
    runs-on: ubuntu-latest

    steps:
    # - uses: actions/checkout@v2
    #   with:
    #     ref: ''
    - name: merge
      run: |
        git config --global user.email "my@wrmsoftware.com"
        git config --global user.name "Merge script"
        git clone https://mywrm:${{ env.access_token }}@github.com/my-wrm/dummy-project.git
        Start-Sleep -s 3
        cd dummy-project
        git fetch origin
        git checkout ${{ github.event.pull_request.base.ref }}
        git merge --no-ff origin/${{ github.event.pull_request.head.ref }}
        git remote -v
        git push origin

    - name: Send greeting
      run: |
        echo ">> ${{ toJSON(github.event.pull_request) }}"

#   Job1:
#     name: Job1
#     runs-on: ubuntu-latest
#     if: github.event.pull_request.base.ref == 'master'   # check the target branch if it's master
#     steps:
#         - name: trigger
#           run: echo "Hii"
