name: Merge Bot (demo)

on:
  pull_request:
    types:
      - labeled
      - ready_for_review
      - review_request_removed
      - review_requested
      - synchronize
      - unlabeled
  pull_request_review:
    types:
      - dismissed
      - submitted

jobs:
  merge:
    runs-on: ubuntu-latest
    name: Merge
    steps:
    - name: Integration check
      uses: squalrus/merge-bot@v0.4.5
      with:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        test: false
        reviewers: false
        labels: ready, merge
        blocking_labels: do not merge
        checks_enabled: false
        method: squash
        delete_source_branch: false