name: CI notify

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["Deploy"]
    types:
      - completed

env:
  target_env: dev
  ready_label: ready to deploy
  deployed_label: deployed
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  notify-on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Set Timezone
      uses: szenius/set-timezone@v1.0
      with:
        timezoneLinux: "Asia/Bangkok"

    - name: Create a Issue
      run: |
        echo $"### Deployed Complete via Workflow [${{ github.event.workflow_run.name }} #${{ github.event.workflow_run.run_number }}](${{ github.event.workflow_run.html_url }})" > issue.txt
        echo $"Pull requests:" >> issue.txt
        gh pr list --label '${{ env.ready_label }}' --state merged --repo ${{ github.event.repository.full_name }} > pr.txt
        while read PR_ITEM; do
          PR_NUMBER=$(echo $PR_ITEM | awk '{ print $1 }')
          echo "- #$PR_NUMBER" >> issue.txt
        done < pr.txt
        gh issue create --title "Deployed to ${{ env.target_env }}" --body-file "issue.txt" --repo ${{ github.event.repository.full_name }}
        
    - name: Update Deploy Status on Pull Request
      run: |
        while read PR_ITEM; do
          PR_NUMBER=$(echo $PR_ITEM | awk '{ print $1 }')
          gh pr edit $PR_NUMBER --remove-label '${{ env.ready_label }}' --repo ${{ github.event.repository.full_name }}
          gh pr edit $PR_NUMBER --add-label '${{ env.deployed_label }}' --repo ${{ github.event.repository.full_name }}
          echo "::notice title=Deployed Pull Request::#$PR_ITEM"
        done < pr.txt

    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}

  notify-on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
    - name: Fail
      run: |
        echo "Fail"
  
  